version: "3.8"

services:
  sequelize-miagrate-pg:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sequelize-miagrate-pg
